name: NSE Archive Test

on:
  workflow_dispatch:

jobs:
  test-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Test Static Archive Download
        run: |
          python <<EOF
          import requests

          url ="https://archives.nseindia.com/content/historical/EQUITIES/2024/NOV/cm01NOV2024bhav.csv.zip"

          response = requests.get(url)

          print("Status Code:", response.status_code)
          print("Content Size:", len(response.content))
          EOF
